apiVersion: v1
kind: Pod
metadata:
  name: retriever
  namespace: postgres
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: my-backup-pvc
          mountPath: /backup
      resources:
        requests:
          memory: "16Mi"
          cpu: "125m"
        limits:
          memory: "128Mi"
          cpu: "1"
  volumes:
    - name: my-backup-pvc
      persistentVolumeClaim:
        claimName: my-backup-pvc
