apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "=1.7.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 120m
