apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nack
  namespace: nats
spec:
  interval: 1m
  chart:
    spec:
      chart: "nack"
      version: ">=0.13"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: configmap-nack
      valuesKey: nack-values.yaml
  targetNamespace: nats