apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap-nginx
    namespace: ingress-nginx
    files:
      - ./ingress/values.yaml 
  - name: configmap-cockroachdb
    namespace: cockroachdb
    files:
      - ./storage/cockroachdb/values.yaml             
generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
  - ./certs/cloud-cert-issuer-staging.yaml
  - ./metrics/helm-release.yaml
  - ./metrics/helm-repository.yaml
