# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OVphVlRZT0o3ZE04TlRv
            RHZSSkZ6RktISnpCYVMxOHhDZjU5VmNjc2w0CkQwSnZxWCt5UVdZbFlVQnp3RXBC
            bUl4QjZDcDlBelRxY0pEQndoLzl6RGMKLS0tIC95RkFjd0R4WUEvQUp0bkFBMXZN
            QmVNeEpQYnNOS3JEWlJ1VTM0TzNIRkEKG2Fy05QPNlwzU4JrxSn6BX/b8aif3HM1
            NRwe0oxEkv45AUPS3MT3i+2rLf722pn1Qfw5SbesKWK1OOhVupN67g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T02:06:31Z"
    mac: ENC[AES256_GCM,data:Ya231LNhjPI822KGHqhovGzI2WO/gfjmFjZhGO0y89oKTmjfHuAMQNx9QX5A+V++UZfO1ps7UnIiOKjlI4ZcRVGlB9/C2KIMxtAkUNJILm+LZ4kjnMbOWj6BHKtW+vddoqizKTnmmRwhX6GI3EGGP73MWw76kWxN0z53KN27xi4=,iv:/pMVCuw//hbF7UL3nChXMI+jiBOULDm2mcm4DjZooy4=,tag:c1ljNa5kZy6iGWQKKUjgQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:KNwVw5Eospw=,iv:4qEcNpHJYozxvTGGcrU2TrP0b3TXKZs2Uqet9TwcpKw=,tag:Mq7r7kpABuLDuTH339w8KQ==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:/Q16mWrCGhQ=,iv:dPocJR3L2S2kClnmLclc4GszUpOsTyXhQBPqOxwLmQ0=,tag:N1THIl/qUXbPjkBMs9Yr2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OVphVlRZT0o3ZE04TlRv
            RHZSSkZ6RktISnpCYVMxOHhDZjU5VmNjc2w0CkQwSnZxWCt5UVdZbFlVQnp3RXBC
            bUl4QjZDcDlBelRxY0pEQndoLzl6RGMKLS0tIC95RkFjd0R4WUEvQUp0bkFBMXZN
            QmVNeEpQYnNOS3JEWlJ1VTM0TzNIRkEKG2Fy05QPNlwzU4JrxSn6BX/b8aif3HM1
            NRwe0oxEkv45AUPS3MT3i+2rLf722pn1Qfw5SbesKWK1OOhVupN67g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T02:06:31Z"
    mac: ENC[AES256_GCM,data:Ya231LNhjPI822KGHqhovGzI2WO/gfjmFjZhGO0y89oKTmjfHuAMQNx9QX5A+V++UZfO1ps7UnIiOKjlI4ZcRVGlB9/C2KIMxtAkUNJILm+LZ4kjnMbOWj6BHKtW+vddoqizKTnmmRwhX6GI3EGGP73MWw76kWxN0z53KN27xi4=,iv:/pMVCuw//hbF7UL3nChXMI+jiBOULDm2mcm4DjZooy4=,tag:c1ljNa5kZy6iGWQKKUjgQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
