# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUkxZkNvUC91ajJDUUZv
            eGhKOGdkaXE2TlRhYlVrNEUzcTQ2c3VvaDFFCmpNR2MrQ1c4OFVsc3p6QVJRR05I
            QVdNS0ZacTRtWDI2TkM3U0oycVRtRVEKLS0tIHhmODIrNDE1b3QrcGNuYWt1bktW
            cGdRZUZ0YjdnelY0TU9QSzlTYzZES0UKFTqy5qYgRLO4/FgrVprvEp/61vwSULpg
            v4M/zkThB8yHMRSxqCvQ+iE7t6R8cY03qcJ/Ky7fk6kwLcLs3gGocQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T09:47:20Z"
    mac: ENC[AES256_GCM,data:U/Nj58gMV9oHJpKwT6bh5T/3fH8/9BvwhQI7GQYic+uUEII14ZaqEvRDm4kfWDxUSsJTqmmVXMduup+ptO4GUVz2CQpZfCN4nwS+v8T2O6ESINDSF16YwVaTr8vlYJfQ1Cg6VcaTcamtE5U87IKxReM91QaXGrMCLN1JV0N7u58=,iv:v+AMwsgCgFW+x8DDwgVxO91z2PWn3iRAcUwrPwvCVGo=,tag:tBlKoIFu2hsObg4ZcXcJsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:S+lzT8fCRMc=,iv:gPz4DpSDaNXr8Roj5nTjvrqSwqKce5aDGUNsx+stxzo=,tag:xtq5AkzycmFPLVjnK8y4Mg==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:le474EQkIvg=,iv:jviaMbXwfYso0C48X2D5jn9hM2L1/VdhSDBKsf0usBQ=,tag:KfMorfHH0d3wX9e0o1npqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUkxZkNvUC91ajJDUUZv
            eGhKOGdkaXE2TlRhYlVrNEUzcTQ2c3VvaDFFCmpNR2MrQ1c4OFVsc3p6QVJRR05I
            QVdNS0ZacTRtWDI2TkM3U0oycVRtRVEKLS0tIHhmODIrNDE1b3QrcGNuYWt1bktW
            cGdRZUZ0YjdnelY0TU9QSzlTYzZES0UKFTqy5qYgRLO4/FgrVprvEp/61vwSULpg
            v4M/zkThB8yHMRSxqCvQ+iE7t6R8cY03qcJ/Ky7fk6kwLcLs3gGocQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T09:47:20Z"
    mac: ENC[AES256_GCM,data:U/Nj58gMV9oHJpKwT6bh5T/3fH8/9BvwhQI7GQYic+uUEII14ZaqEvRDm4kfWDxUSsJTqmmVXMduup+ptO4GUVz2CQpZfCN4nwS+v8T2O6ESINDSF16YwVaTr8vlYJfQ1Cg6VcaTcamtE5U87IKxReM91QaXGrMCLN1JV0N7u58=,iv:v+AMwsgCgFW+x8DDwgVxO91z2PWn3iRAcUwrPwvCVGo=,tag:tBlKoIFu2hsObg4ZcXcJsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
