# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVXp2MU1NbmpUclBXSzAw
            bUdOUDFuTUp1RlY3aFF4R3NDRmpmSWhwYmdvCnRXZlBWM21IM1hac3paNXBkRk1J
            K2xlZDkwWnBNN3VLZUQwZkp3d2FOZjgKLS0tIDNuamx3d2F6WGZ6N05pSUUxUXZt
            eEhZbVRWU0NYZHJtenNMdFZwRHI4QlEKJMvKNm20RUFHe2DUxH1Hw2nMpUhv0+YR
            SjZgZK+kfs7gI981jwnC+0adDxyy6bHLMFZ5sJ2+MwYk01ilVmj81g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T02:30:55Z"
    mac: ENC[AES256_GCM,data:F+Fil4DRHz52tQMztI4gh/e83DFxCGfK7yJftKdKkxLPyaxwex5fZrr5fd1eKST1+UjdBlqvU5PVtP1YjHbEkybyXOZ110q12dpJQcsF8ndBNXH4S/HvbbNHF0pKlERvCQqR11jXAuVHH/18120UiwvllF3scol5rwoE/cgX5NE=,iv:7W5uL64B28TPE75ynWFEo5xZ2yr4H6vGDyAbh1HmMRE=,tag:3xbIWI+3jL1apDuAsxvUKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:XNKRSwrVhLw=,iv:rHNkP+KNAX009Axt9G+8AvhkLXsfnU+k7CkouCl3txQ=,tag:crbCGZ+zmJxsn7V/Eot+0Q==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:0SuZHCRrqSQ=,iv:FuT9ZMDSGewhaX8Nz4USDn+k5a7I19Hp3KI7XbddWkA=,tag:nffK3iFo3WrFTGSEGhYPbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVXp2MU1NbmpUclBXSzAw
            bUdOUDFuTUp1RlY3aFF4R3NDRmpmSWhwYmdvCnRXZlBWM21IM1hac3paNXBkRk1J
            K2xlZDkwWnBNN3VLZUQwZkp3d2FOZjgKLS0tIDNuamx3d2F6WGZ6N05pSUUxUXZt
            eEhZbVRWU0NYZHJtenNMdFZwRHI4QlEKJMvKNm20RUFHe2DUxH1Hw2nMpUhv0+YR
            SjZgZK+kfs7gI981jwnC+0adDxyy6bHLMFZ5sJ2+MwYk01ilVmj81g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T02:30:55Z"
    mac: ENC[AES256_GCM,data:F+Fil4DRHz52tQMztI4gh/e83DFxCGfK7yJftKdKkxLPyaxwex5fZrr5fd1eKST1+UjdBlqvU5PVtP1YjHbEkybyXOZ110q12dpJQcsF8ndBNXH4S/HvbbNHF0pKlERvCQqR11jXAuVHH/18120UiwvllF3scol5rwoE/cgX5NE=,iv:7W5uL64B28TPE75ynWFEo5xZ2yr4H6vGDyAbh1HmMRE=,tag:3xbIWI+3jL1apDuAsxvUKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
