# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a25uc0lxZWNDaVdHVjlk
            cmJQc1lXY0hQYnl0Y2FpbGxpMU10d0lSeUc4ClcrMys5MnhFSitPRUREZXBNWGFi
            alA1RGpFajI2M203SzFQK2Q1QVZqMFUKLS0tIHl2OG1aSEFOTU9tV1luNjZVNmF0
            K2VqR3pRYUtDaVJjRCtyMjlvYjJJbWcKoRr/hzcDXF0BUKmmVuHtqdtEx1KQ5FL9
            I3JtmZULGGDcYsG4n05SKB5oOyklZIMTUmammeAqC6Dj3LDbWVikPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-25T08:49:26Z"
    mac: ENC[AES256_GCM,data:DQPEHAwqCRLCbgDDJjk6WrRGrtuUzehzS1EojgEuPOdhSyPnDBqRkKcP90YW97v/t9MQ8Yxw8WFYM0PY8xhtmEVnDH3PoFcdvQIs7tGZYowsBaGVlWKjLWOREGev5oyAkdwlu4iyc7LDY3xiNfHRrpDH+7w/WLVM5GFY51ojFzU=,iv:T5EzVNJxlBs7S23Z7nhuhHiRaZFB0nj0Wg4OcwGWNbU=,tag:Sn1DTsxp+Iy3L23XKg0Wcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:LYJbPeVgxiY=,iv:JWHZ9C4BgftXpBXa3S+5x4Cqn1yZFLUAPZfeAA8gJxU=,tag:tDc5cSMcVsOlZNWNISyE1w==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:AFJTtdWbaYE=,iv:NBhHDUx8xQk0LofhOcjezmpbE9trYjxfgVilW0W14A0=,tag:oGB0JQKT61EMqlMfJNG9lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a25uc0lxZWNDaVdHVjlk
            cmJQc1lXY0hQYnl0Y2FpbGxpMU10d0lSeUc4ClcrMys5MnhFSitPRUREZXBNWGFi
            alA1RGpFajI2M203SzFQK2Q1QVZqMFUKLS0tIHl2OG1aSEFOTU9tV1luNjZVNmF0
            K2VqR3pRYUtDaVJjRCtyMjlvYjJJbWcKoRr/hzcDXF0BUKmmVuHtqdtEx1KQ5FL9
            I3JtmZULGGDcYsG4n05SKB5oOyklZIMTUmammeAqC6Dj3LDbWVikPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-25T08:49:26Z"
    mac: ENC[AES256_GCM,data:DQPEHAwqCRLCbgDDJjk6WrRGrtuUzehzS1EojgEuPOdhSyPnDBqRkKcP90YW97v/t9MQ8Yxw8WFYM0PY8xhtmEVnDH3PoFcdvQIs7tGZYowsBaGVlWKjLWOREGev5oyAkdwlu4iyc7LDY3xiNfHRrpDH+7w/WLVM5GFY51ojFzU=,iv:T5EzVNJxlBs7S23Z7nhuhHiRaZFB0nj0Wg4OcwGWNbU=,tag:Sn1DTsxp+Iy3L23XKg0Wcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
