# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeGVzZCtSK1JhZjlNcjVF
            dmVLTXprellkVUVPVVg1TzUyL2w2UEw1Ym1rCjZFay9aT2FwbmRxZE42QkxMUlhw
            WUZPa3dBN3hJc2FrMmVrUFJzOFExdDAKLS0tIG1DYlJXVFRNeTZOZjFueC9pc2p1
            a2pwT2pFYlp5U2NuOHRrdHAvSDFtS0UK5IRZV/X/yE8yvYIotaPZH85GcBScv214
            otHY7P5LQxqHWgRrB9bmTWG773u1lSQvd7POyL7s2nQSFsuLHDwC9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-26T08:53:08Z"
    mac: ENC[AES256_GCM,data:+QiRItxDk3RQtpF9CU5MzSIGEmFyY1pFaGX+tclIJ8F3oHK5XtQfAhiitWUMSfE15Lae9j1oRKO0upLCGoju9lJ7bLrpL15s9A5p65iVaPv7bm7F3DzAqzjWIHSMwhjwsv3hyNtbiwLZjF+PuWZBRjnjYydQF8wcQbf7wO8LLO8=,iv:4gpGzpQQpqoMzjx0Q1BTy6fDXB2bExsPUvyTQs/k+0c=,tag:2BtViBApRxKOJiBrdRBWxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:8OAlWl0+qDQ=,iv:WTWXKlgUPLOqEQC1dYua0c8qQtZ5/Y+fnz49/a0+kQk=,tag:ZLsl8FBro8GVAQFerkO7Xw==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:Pc9jEM1uC60=,iv:/zlXEHvxIaGyZ9KfJyfc5XaNa5jIHAqn+MgibSCQ7hE=,tag:Bbvmo6ObwP4iY86JxGn3nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeGVzZCtSK1JhZjlNcjVF
            dmVLTXprellkVUVPVVg1TzUyL2w2UEw1Ym1rCjZFay9aT2FwbmRxZE42QkxMUlhw
            WUZPa3dBN3hJc2FrMmVrUFJzOFExdDAKLS0tIG1DYlJXVFRNeTZOZjFueC9pc2p1
            a2pwT2pFYlp5U2NuOHRrdHAvSDFtS0UK5IRZV/X/yE8yvYIotaPZH85GcBScv214
            otHY7P5LQxqHWgRrB9bmTWG773u1lSQvd7POyL7s2nQSFsuLHDwC9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-26T08:53:08Z"
    mac: ENC[AES256_GCM,data:+QiRItxDk3RQtpF9CU5MzSIGEmFyY1pFaGX+tclIJ8F3oHK5XtQfAhiitWUMSfE15Lae9j1oRKO0upLCGoju9lJ7bLrpL15s9A5p65iVaPv7bm7F3DzAqzjWIHSMwhjwsv3hyNtbiwLZjF+PuWZBRjnjYydQF8wcQbf7wO8LLO8=,iv:4gpGzpQQpqoMzjx0Q1BTy6fDXB2bExsPUvyTQs/k+0c=,tag:2BtViBApRxKOJiBrdRBWxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
