# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMzN0blJBUlNnYVFYd1pn
            NmxoSmYyaXAzSjBvRWpZTFI0dEtXb0M5SlNFCkw2TkJ3K0N2ci9tc1l2WHFPOXYv
            cy9CWjFHVEE1dVF6MG04dDJhbE5JYWMKLS0tIEx3V3VBdCtWbWcwUWVzSmdhd1hv
            S28yYytYZEEvdURDSG9rSEtaT29UWkEKgJ++G+mJGGOZBzEOnXQkMlRKZBtQ3MOJ
            44fbxcXi5D5lWJmg5ZLJg2XZkEf6JqnRdXFdDRpmQGtwjPfmK3yvvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-14T12:26:45Z"
    mac: ENC[AES256_GCM,data:aIWZTTsPeaCnvDRkKagloH9BtJhHrx3VegycsHGfm8ijYqe5Z1BHIc1WgQcHaicvFUZdgzRxWb1Yw7QrAjRlcUFNzq+of4mPU38t9Ln1gKGl7ZeSoxAqawHUc0Gsu9/GeUAMbmkhVG802zeZyM5mDE+GQ4TWNLnbWnds4jVjH04=,iv:GFg4d/fCDW1TGRgjetsKUwd+gZuyioHkBzzmjPhJyYk=,tag:D0EnzNl/kui+T7nB7K9Qaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:i/VCjdILT9I=,iv:9g+rCctZe2cwP8pmqtzvsiGAU+oSe44ahm/eN5W+W0Q=,tag:qbuNiz7AL9nH9FvYn4OY8Q==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:+nweaCB4C68=,iv:h9r53XkKMFRHsKQGsEGQ54auf5kptcpyhVkZtw/ZE4M=,tag:MDvCJIHEZBWWblNb3J0WWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMzN0blJBUlNnYVFYd1pn
            NmxoSmYyaXAzSjBvRWpZTFI0dEtXb0M5SlNFCkw2TkJ3K0N2ci9tc1l2WHFPOXYv
            cy9CWjFHVEE1dVF6MG04dDJhbE5JYWMKLS0tIEx3V3VBdCtWbWcwUWVzSmdhd1hv
            S28yYytYZEEvdURDSG9rSEtaT29UWkEKgJ++G+mJGGOZBzEOnXQkMlRKZBtQ3MOJ
            44fbxcXi5D5lWJmg5ZLJg2XZkEf6JqnRdXFdDRpmQGtwjPfmK3yvvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-14T12:26:45Z"
    mac: ENC[AES256_GCM,data:aIWZTTsPeaCnvDRkKagloH9BtJhHrx3VegycsHGfm8ijYqe5Z1BHIc1WgQcHaicvFUZdgzRxWb1Yw7QrAjRlcUFNzq+of4mPU38t9Ln1gKGl7ZeSoxAqawHUc0Gsu9/GeUAMbmkhVG802zeZyM5mDE+GQ4TWNLnbWnds4jVjH04=,iv:GFg4d/fCDW1TGRgjetsKUwd+gZuyioHkBzzmjPhJyYk=,tag:D0EnzNl/kui+T7nB7K9Qaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
