# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraUttSzRDaG1jQnBXdmU4
            U3JLU0NHRHNYalFtWVN0cC8zUk9XV2lQMVQ0CkNneCtEaXZDQnIvZWZYL3NmdDBq
            MkxRMGo5Y3ZBT3N0REhvZkJVUmJsMkUKLS0tIFA1eWtUTWZmU0hFdER3elRqVDBs
            VEljQzdTcURUQXNtRFg1U3JQSHhRa1EK2V2AH1qLMaJJOyJHdws+VMF+DF6SOkmw
            KszydFiUbwML2yfrKqZr5/1GvdRxKhjG1e/GzOCHSsbx3UhjAP0Qzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T15:33:04Z"
    mac: ENC[AES256_GCM,data:bOdfPxmENa1YDdDM1f8l3mABuHh0P9uwiR4e0c0BG8IpAbvZtbl1vlLRxt9EFnu0FUHztCBphauDgfVpt2u57KiIdpN1Jt3y432pyswFJ12roetB50eJL3AJSNwd/1vmWL/RxAIDNORfnUlVVzOdNyj55Xtg9S4GmDmwrTw6Pt8=,iv:eGcM8FQYO1h/R29sBwfSB2lYuvuijU/OmAJpkdZRKTs=,tag:UzeerbkiZ02YgOfBQHWbVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:7QGmu2/gI00=,iv:vpfr5nOnh7jelIgdqdlg8OtLhW/JP7Mf0IalKkPBmig=,tag:UpLj85OdYkVg6X5TxaUQOw==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:jY+vf4RQwkk=,iv:3Tv2Gzk/V2heUH3yMyNWtcvjDgjXYytYJOmBLHVaA4Q=,tag:92ros/c/m+7LBHfrQRPRgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraUttSzRDaG1jQnBXdmU4
            U3JLU0NHRHNYalFtWVN0cC8zUk9XV2lQMVQ0CkNneCtEaXZDQnIvZWZYL3NmdDBq
            MkxRMGo5Y3ZBT3N0REhvZkJVUmJsMkUKLS0tIFA1eWtUTWZmU0hFdER3elRqVDBs
            VEljQzdTcURUQXNtRFg1U3JQSHhRa1EK2V2AH1qLMaJJOyJHdws+VMF+DF6SOkmw
            KszydFiUbwML2yfrKqZr5/1GvdRxKhjG1e/GzOCHSsbx3UhjAP0Qzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T15:33:04Z"
    mac: ENC[AES256_GCM,data:bOdfPxmENa1YDdDM1f8l3mABuHh0P9uwiR4e0c0BG8IpAbvZtbl1vlLRxt9EFnu0FUHztCBphauDgfVpt2u57KiIdpN1Jt3y432pyswFJ12roetB50eJL3AJSNwd/1vmWL/RxAIDNORfnUlVVzOdNyj55Xtg9S4GmDmwrTw6Pt8=,iv:eGcM8FQYO1h/R29sBwfSB2lYuvuijU/OmAJpkdZRKTs=,tag:UzeerbkiZ02YgOfBQHWbVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
