# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd21kNXY4bFpzeU5OeERU
            cnBuYi9tbFdQZURDL1ZYazhLV2syamgxL1NNCkFjRzM5NUNDU2svYmJiOHNKODVp
            cDkzWDhtNk9qaXZxTEhQaFpWU3c4dGcKLS0tIGRQU2p1UGkwRmZjT2NLRmZINC8z
            RVFxWmxqNUpLQk5BeE8vQTcvTGhFbWsKmznc8f6z5cWisyfJVe8AYbUtVecm691A
            0kFQlJMFxSxhr+oMKOC8rv5BF7mmb53uq1Eul4+vbDgbD1M3lAzuKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-28T08:22:59Z"
    mac: ENC[AES256_GCM,data:G6ApNh6EW4x0hbXNzfNm3TqaspSrDMz4bLvIczG8riJBbKhVTHQ+dSPWikAr+siIX0c2Jhe2c8CIAtM+jpwVXf/VEda5fCyCJykaHjAtpjk1WYrSL2b54SVapT+sq2Zm5lVVVldVP6fNlGux7pedORU7YO23Zzvev282dRQvo+Q=,iv:qZCsAdj5w/qlYyDBfNywj+SdT7Ls0mmbraI0bXg+OiI=,tag:Pd4PgN0fc7pobAgZFC+tGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:04nPztqDGVU=,iv:wnj0wrXSDQw0XNO23Ut0fzsXW58IHIrwWOQ3vAsIdn0=,tag:Q5hZ3PfyJuJoIRn/2BYQxA==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:q2+jItBwv6E=,iv:fjKOX1qpZ28GT+DIMz+HTTbBPeM5SP+T42GQeoWXbhw=,tag:pUwlB9ljIxdWY9Lvyd0P5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd21kNXY4bFpzeU5OeERU
            cnBuYi9tbFdQZURDL1ZYazhLV2syamgxL1NNCkFjRzM5NUNDU2svYmJiOHNKODVp
            cDkzWDhtNk9qaXZxTEhQaFpWU3c4dGcKLS0tIGRQU2p1UGkwRmZjT2NLRmZINC8z
            RVFxWmxqNUpLQk5BeE8vQTcvTGhFbWsKmznc8f6z5cWisyfJVe8AYbUtVecm691A
            0kFQlJMFxSxhr+oMKOC8rv5BF7mmb53uq1Eul4+vbDgbD1M3lAzuKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-28T08:22:59Z"
    mac: ENC[AES256_GCM,data:G6ApNh6EW4x0hbXNzfNm3TqaspSrDMz4bLvIczG8riJBbKhVTHQ+dSPWikAr+siIX0c2Jhe2c8CIAtM+jpwVXf/VEda5fCyCJykaHjAtpjk1WYrSL2b54SVapT+sq2Zm5lVVVldVP6fNlGux7pedORU7YO23Zzvev282dRQvo+Q=,iv:qZCsAdj5w/qlYyDBfNywj+SdT7Ls0mmbraI0bXg+OiI=,tag:Pd4PgN0fc7pobAgZFC+tGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
