# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmM5RUpHZU5rZ0Z1U204
            ZmFUM1lRcjZWS29HYWVFVHBHa2lYQU1XeXlBCm15OXVCbXgzbDQ4STRzc2ZlbERX
            c2RYaXorbDRZbDlra2xVM2gxR1QwUzQKLS0tIHNYRzlIZHFjUzBveldDd1Z3KzlO
            aDM1TWFCNmVYNEpuZEtuVWZxOWppRTAKQmYMvBe2prbpbiG1UNEd8fSGm5IIqpxQ
            X5kont4ix4lFjzOi1zPhJAz/ZwohWL5sKBqFTyQjPR3UCu85cH0NgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T16:16:25Z"
    mac: ENC[AES256_GCM,data:9IhZadzYjMjwcBocL2asEqC21HuOo5BivYZaPHkYoeAwPBm1OcGj6g2n0K8aTLXRdfilZa8lNoh8yce1H/YlFWKmF/f1iuabhzL/GJzrlW1Mgu6qPLhEgy9SpXDgJOpmtgKEKM5Ony4jUaLUicS3rZW6qJWBr2yrjtLVmDODEeI=,iv:vfyrWPMKHIAwat7UM4pYYPKD7//bV81V9uHgFnW6Tas=,tag:1bSLrE1cdO6rhJiTE1pv3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:Au25U399bYE=,iv:rBh8eygGnp/0DXvfwtKGq3sKo/QgDGfdP1E6TaOXfIM=,tag:wZ9kcVIL5RaXzQp7RU8TgQ==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:rnn5sUzAE5w=,iv:RW4flGXbdd7l6Whhn5hQS+LIilLaXGe/Rq77imaWTbs=,tag:EP2PDM3EkOqcxVEyrjdTbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmM5RUpHZU5rZ0Z1U204
            ZmFUM1lRcjZWS29HYWVFVHBHa2lYQU1XeXlBCm15OXVCbXgzbDQ4STRzc2ZlbERX
            c2RYaXorbDRZbDlra2xVM2gxR1QwUzQKLS0tIHNYRzlIZHFjUzBveldDd1Z3KzlO
            aDM1TWFCNmVYNEpuZEtuVWZxOWppRTAKQmYMvBe2prbpbiG1UNEd8fSGm5IIqpxQ
            X5kont4ix4lFjzOi1zPhJAz/ZwohWL5sKBqFTyQjPR3UCu85cH0NgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T16:16:25Z"
    mac: ENC[AES256_GCM,data:9IhZadzYjMjwcBocL2asEqC21HuOo5BivYZaPHkYoeAwPBm1OcGj6g2n0K8aTLXRdfilZa8lNoh8yce1H/YlFWKmF/f1iuabhzL/GJzrlW1Mgu6qPLhEgy9SpXDgJOpmtgKEKM5Ony4jUaLUicS3rZW6qJWBr2yrjtLVmDODEeI=,iv:vfyrWPMKHIAwat7UM4pYYPKD7//bV81V9uHgFnW6Tas=,tag:1bSLrE1cdO6rhJiTE1pv3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
