# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
    name: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNDF6a0lreDEyN05paU9I
            Ynh4ZFpxMWhJSXdoZFBZLzZsL1NIamhxVUVBCnZSYURIZVhNc2ZrOU5LTXgxY2tX
            dFVKNGRvdFg3Z3I2U0NOL09renN1R0EKLS0tIHkvc0Mxd3JZRU5aeUtxZEtHT1Nl
            Q3Q0WXBNNHNCV1ZKandaZlIwQVY1V1kK7LJcONNo68g57gNTG2+RMkxEtUaBWdRh
            em+RhY6yS/BZVgIwyOTAONjZ67D8er4Y0eIVA8mLonTNYCpGJlU0og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T14:44:50Z"
    mac: ENC[AES256_GCM,data:qOMf+0/jENuDDR0hNe+NeJiaricucWWr2XdDB6rzl1x2pS4mujtFYAzYts9ZMHkX24ecR+DDk3rRIK4kyNh98A+t6UvhXOpG/7A/9X3CREHsbIcGLYs2wAXR8Kx8OxQxFVu8je769ClNZxs6nOSZyx1lMXqCB9gNGBfks/U/NrU=,iv:3ZGicm/i6MvZ7pbTwA4qUnKac7zfKJne7yVmwXPrfrk=,tag:JQ8lKrrekfjIuXgnq9BzHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: local-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:M5/FxN3Scl4=,iv:UrPyEKmXPIvUot/nbIbuytV7cVa2adFzVU9EjyfQarg=,tag:BuNfGRKL21qxOLic9AxosQ==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:dzDnBZKWLC4=,iv:Rh698aPXr1sUkC7dSNIDqJL4z9con3uQgOEK8/3wceo=,tag:blj//Y3gnzLKFpVXt/YR/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pf8qp9ll4smp2j9p3yhacslle3fc44jveec57npa0eagm0sz40q4kkd7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNDF6a0lreDEyN05paU9I
            Ynh4ZFpxMWhJSXdoZFBZLzZsL1NIamhxVUVBCnZSYURIZVhNc2ZrOU5LTXgxY2tX
            dFVKNGRvdFg3Z3I2U0NOL09renN1R0EKLS0tIHkvc0Mxd3JZRU5aeUtxZEtHT1Nl
            Q3Q0WXBNNHNCV1ZKandaZlIwQVY1V1kK7LJcONNo68g57gNTG2+RMkxEtUaBWdRh
            em+RhY6yS/BZVgIwyOTAONjZ67D8er4Y0eIVA8mLonTNYCpGJlU0og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T14:44:50Z"
    mac: ENC[AES256_GCM,data:qOMf+0/jENuDDR0hNe+NeJiaricucWWr2XdDB6rzl1x2pS4mujtFYAzYts9ZMHkX24ecR+DDk3rRIK4kyNh98A+t6UvhXOpG/7A/9X3CREHsbIcGLYs2wAXR8Kx8OxQxFVu8je769ClNZxs6nOSZyx1lMXqCB9gNGBfks/U/NrU=,iv:3ZGicm/i6MvZ7pbTwA4qUnKac7zfKJne7yVmwXPrfrk=,tag:JQ8lKrrekfjIuXgnq9BzHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
