apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster

# configMapGenerator:
#   - name: configmap-nats
#     namespace: nats
#     files:
#       - ./stream/nats/values.yaml
# generatorOptions:
#   disableNameSuffixHash: true

resources:
  - ingress/helm-repository.yaml
  - ingress/namespace.yaml
  - ingress/helm-release.yaml
  - certs/helm-repository.yaml
  - certs/namespace.yaml
  - certs/helm-release.yaml
  - storage/postgres/namespace.yaml
  - storage/postgres/backup.yaml
  - storage/postgres/postgres.yaml
  # - nats/helm-repository.yaml
  # - nats/namespace.yaml
  # - nats/helm-release.yaml