apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster

configMapGenerator:
  - name: configmap-nats
    namespace: nats
    files:
      - ./stream/nats/nats-values.yaml
  - name: configmap-nack
    namespace: nats
    files:
      - ./stream/nats/nack-values.yaml      
  - name: configmap-opentelemetry-collector
    namespace: observability
    files:
      - ./observability/opentelemetry/values.yaml   
  - name: configmap-cockroachdb
    namespace: cockroachdb
    files:
      - ./storage/cockroachdb/values.yaml                     
generatorOptions:
  disableNameSuffixHash: true

resources:
  - ingress/helm-repository.yaml
  - ingress/namespace.yaml
  - ingress/helm-release.yaml
  - certs/helm-repository.yaml
  - certs/namespace.yaml
  - certs/cloud-cert-issuer.yaml
  - certs/helm-release.yaml
  - observability/namespace.yaml  
  - observability/opentelemetry/helm-repository.yaml
  - observability/opentelemetry/helm-release.yaml
  - observability/jaeger/helm-repository.yaml
  - observability/jaeger/helm-release.yaml  
  #  need to be commented otherwise because it needs to wait for jaeger operator
  # - observability/jaeger/jaegertracing.yaml    
  #  need to be commented otherwise because it needs to wait for cert-manager
  # - storage/cockroachdb/helm-release.yaml  
  - storage/cockroachdb/helm-repository.yaml 
  - storage/cockroachdb/namespace.yaml
  # - storage/postgres/namespace.yaml
  # - storage/postgres/backup.yaml
  # - storage/postgres/postgres.yaml  
  - stream/nats/helm-repository.yaml
  - stream/nats/namespace.yaml
  # - stream/nats/nats-helm-release.yaml
  # - stream/nats/nack-helm-release.yaml