apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.12.1"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: configmap-opentelemetry-collector
