apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-server-tls
  namespace: nats
spec:
  secretName: nats-server-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: mkcert-cluster-issuer
    kind: ClusterIssuer
  commonName: nats-nats.nats.svc.cluster.local
  dnsNames:
  - nats-nats
  - nats-nats.nats
  - nats-nats.nats.svc
  - nats-nats.nats.svc.cluster.local
  - '*.nats-nats'
  - '*.nats-nats.nats'
  - '*.nats-nats.nats.svc'
  - '*.nats-nats.nats.svc.cluster.local'