# we can only create it before
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: local-postgres-secret
  namespace: postgres
type: Opaque
stringData:
  superUserPassword: DB_PASSWORD
  replicationUserPassword: DB_PASSWORD
