apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger-operator
      version: ">=0.5"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      interval: 1m
  targetNamespace: observability
