apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger-operator
      version: "=2.29"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: observability
      interval: 1m