# https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger-operator
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaegertracing 
  namespace: flux-system
spec:
  interval: 1m
  url: https://jaegertracing.github.io/helm-charts