apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: metrics-server
      version: "3.8.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
      interval: 1m
