statefulset:
  replicas: 3
storage:
  persistentVolume:
    size: 20Gi
tls:
  certs:
    selfSigner:
      enabled: false
    certManager: true
    certManagerIssuer:
      kind: ClusterIssuer
      name: mkcert-cluster-issuer
    useCertManagerV1CRDs: true      